In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df =pd.read_csv('diabetes.csv')

In [ ]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [ ]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [ ]:
X =df.iloc[:,:-1].values
y=df.iloc[:,-1].values

In [ ]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X=scaler.fit_transform(X)

In [ ]:
X.shape

(768, 8)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [107]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Dropout

In [ ]:
model =Sequential()
model.add(Dense(32,activation='relu',input_dim=8))
model.add(Dense(1,activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
model.fit(X_train,y_train,batch_size=32,epochs=100,validation_data=(X_test,y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7983 - loss: 0.4528 - val_accuracy: 0.8182 - val_loss: 0.4356
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7680 - loss: 0.4785 - val_accuracy: 0.8182 - val_loss: 0.4321
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7667 - loss: 0.4714 - val_accuracy: 0.8182 - val_loss: 0.4300
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7526 - loss: 0.5033 - val_accuracy: 0.8182 - val_loss: 0.4273
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7968 - loss: 0.4371 - val_accuracy: 0.8182 - val_loss: 0.4263
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7817 - loss: 0.4676 - val_accuracy: 0.8182 - val_loss: 0.4239
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7765 - loss: 0.4657 - val_accuracy: 0.8182 - val_loss: 0.4235
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7836 - loss: 0.4497 - val_accuracy: 0.8182 - val_loss: 0.4223
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7721 - loss: 0.4610 - val_accuracy: 0.8182 - val_loss: 0.4224
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7686 - loss: 0.4520 - val_accuracy: 0.8117 - val_loss: 0.4222
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7886 - loss: 0.4309 - val_accuracy: 0.8117 - val_loss: 0.4206
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7411 - loss: 0.4975 - val_accuracy: 0.8117 - val_loss: 0.4207
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7941 - loss: 0.4373 - val_accuracy: 0.8117 - val_loss: 0.4199
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7831 - loss: 0.4652 - val_accuracy: 0.8117 - val_loss: 0.4206
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7867 - loss: 0.4413 - val_accuracy: 0.8117 - val_loss: 0.4210
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7672 - loss: 0.4737 - val_accuracy: 0.8117 - val_loss: 0.4219
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7771 - loss: 0.4628 - val_accuracy: 0.8117 - val_loss: 0.4210
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7748 - loss: 0.4548 - val_accuracy: 0.8182 - val_loss: 0.4203
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8142 - loss: 0.4285 - val_accuracy: 0.8182 - val_loss: 0.4191
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7974 - loss: 0.4386 - val_accuracy: 0.8117 - val_loss: 0.4221
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7999 - loss: 0.4271 - val_accuracy: 0.8117 - val_loss: 0.4225
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8087 - loss: 0.4350 - val_accuracy: 0.8247 - val_loss: 0.4204
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8107 - loss: 0.4372 - val_accuracy: 0.8247 - val_loss: 0.4199
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7880 - loss: 0.4465 - val_accuracy: 0.8117 - val_loss: 0.4225
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7590 - loss: 0.4873 - val_accuracy: 0.8117 - val_loss: 0.4217
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8056 - loss: 0.4322 - val_accuracy: 0.8117 - val_loss: 0.4220
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7654 - loss: 0.4574 - val_accuracy: 0.8052 - val_loss: 0.4221
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7984 - loss: 0.4282 - val_accuracy: 0.8052 - val_loss: 0.4222
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8089 - loss: 0.4184 - val_accuracy: 0.8052 - val_loss: 0.4228
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7955 - loss: 0.4329 - val_accuracy: 0.8052 - val_loss: 0.4233
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7747 - loss: 0.4634 - val_accuracy: 0.8117 - val_loss: 0.4231
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7756 - loss: 0.4426 - val_accuracy: 0.8052 - val_loss: 0.4217
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7890 - loss: 0.4579 - val_accuracy: 0.8117 - val_loss: 0.4230
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7923 - loss: 0.4250 - val_accuracy: 0.8117 - val_loss: 0.4240
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7958 - loss: 0.4507 - val_accuracy: 0.8117 - val_loss: 0.4247
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7886 - loss: 0.4450 - val_accuracy: 0.8182 - val_loss: 0.4250
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8009 - loss: 0.4197 - val_accuracy: 0.8182 - val_loss: 0.4255
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8077 - loss: 0.4103 - val_accuracy: 0.8117 - val_loss: 0.4251
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7816 - loss: 0.4449 - val_accuracy: 0.8117 - val_loss: 0.4276
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7927 - loss: 0.4496 - val_accuracy: 0.8117 - val_loss: 0.4267
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8112 - loss: 0.3953 - val_accuracy: 0.8052 - val_loss: 0.4261
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7993 - loss: 0.4163 - val_accuracy: 0.7922 - val_loss: 0.4275
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8043 - loss: 0.4194 - val_accuracy: 0.8052 - val_loss: 0.4271
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7838 - loss: 0.4195 - val_accuracy: 0.8052 - val_loss: 0.4300
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7710 - loss: 0.4467 - val_accuracy: 0.8052 - val_loss: 0.4293
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7709 - loss: 0.4443 - val_accuracy: 0.8052 - val_loss: 0.4286
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7829 - loss: 0.4449 - val_accuracy: 0.8117 - val_loss: 0.4282
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7976 - loss: 0.4125 - val_accuracy: 0.8117 - val_loss: 0.4293
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8025 - loss: 0.4156 - val_accuracy: 0.8117 - val_loss: 0.4296
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8098 - loss: 0.4035 - val_accuracy: 0.8052 - val_loss: 0.4283
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8260 - loss: 0.4070 - val_accuracy: 0.8117 - val_loss: 0.4296
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7764 - loss: 0.4443 - val_accuracy: 0.8117 - val_loss: 0.4290
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8083 - loss: 0.4275 - val_accuracy: 0.8052 - val_loss: 0.4312
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7801 - loss: 0.4674 - val_accuracy: 0.8117 - val_loss: 0.4305
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8085 - loss: 0.4065 - val_accuracy: 0.8182 - val_loss: 0.4307
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7955 - loss: 0.4256 - val_accuracy: 0.8052 - val_loss: 0.4313
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8161 - loss: 0.4147 - val_accuracy: 0.8117 - val_loss: 0.4301
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8047 - loss: 0.4152 - val_accuracy: 0.8117 - val_loss: 0.4313
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7799 - loss: 0.4200 - val_accuracy: 0.8117 - val_loss: 0.4337
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7971 - loss: 0.4354 - val_accuracy: 0.8182 - val_loss: 0.4320
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8220 - loss: 0.4130 - val_accuracy: 0.8117 - val_loss: 0.4330
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8319 - loss: 0.3934 - val_accuracy: 0.8182 - val_loss: 0.4314
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8191 - loss: 0.3844 - val_accuracy: 0.8052 - val_loss: 0.4333
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7797 - loss: 0.4372 - val_accuracy: 0.8117 - val_loss: 0.4374
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7748 - loss: 0.4394 - val_accuracy: 0.8117 - val_loss: 0.4372
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8100 - loss: 0.4041 - val_accuracy: 0.8182 - val_loss: 0.4358
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4162 - val_accuracy: 0.8247 - val_loss: 0.4365
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7995 - loss: 0.4293 - val_accuracy: 0.8247 - val_loss: 0.4344
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8210 - loss: 0.3863 - val_accuracy: 0.8182 - val_loss: 0.4374
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7956 - loss: 0.4266 - val_accuracy: 0.8052 - val_loss: 0.4367
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7780 - loss: 0.4312 - val_accuracy: 0.8182 - val_loss: 0.4362
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8141 - loss: 0.4074 - val_accuracy: 0.8247 - val_loss: 0.4341
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7791 - loss: 0.4278 - val_accuracy: 0.8182 - val_loss: 0.4362
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7793 - loss: 0.4321 - val_accuracy: 0.8247 - val_loss: 0.4363
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8032 - loss: 0.4099 - val_accuracy: 0.8117 - val_loss: 0.4356
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7832 - loss: 0.4176 - val_accuracy: 0.8117 - val_loss: 0.4348
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8135 - loss: 0.3945 - val_accuracy: 0.8182 - val_loss: 0.4358
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7921 - loss: 0.4202 - val_accuracy: 0.8117 - val_loss: 0.4344
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8162 - loss: 0.3863 - val_accuracy: 0.8182 - val_loss: 0.4366
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7962 - loss: 0.4190 - val_accuracy: 0.8117 - val_loss: 0.4360
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.4099 - val_accuracy: 0.8117 - val_loss: 0.4355
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7887 - loss: 0.4308 - val_accuracy: 0.8117 - val_loss: 0.4370
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4478 - val_accuracy: 0.8182 - val_loss: 0.4372
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8104 - loss: 0.3847 - val_accuracy: 0.8182 - val_loss: 0.4381
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7909 - loss: 0.4388 - val_accuracy: 0.8182 - val_loss: 0.4377
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7991 - loss: 0.3992 - val_accuracy: 0.8182 - val_loss: 0.4384
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8014 - loss: 0.4108 - val_accuracy: 0.8117 - val_loss: 0.4386
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8099 - loss: 0.4061 - val_accuracy: 0.8182 - val_loss: 0.4374
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8308 - loss: 0.3787 - val_accuracy: 0.8247 - val_loss: 0.4375
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7757 - loss: 0.4368 - val_accuracy: 0.8247 - val_loss: 0.4366
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8128 - loss: 0.4009 - val_accuracy: 0.8182 - val_loss: 0.4363
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8080 - loss: 0.4141 - val_accuracy: 0.8182 - val_loss: 0.4364
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8127 - loss: 0.3891 - val_accuracy: 0.8117 - val_loss: 0.4366
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7946 - loss: 0.4375 - val_accuracy: 0.8182 - val_loss: 0.4394
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7942 - loss: 0.4294 - val_accuracy: 0.8182 - val_loss: 0.4380
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8049 - loss: 0.4196 - val_accuracy: 0.8247 - val_loss: 0.4391
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8135 - loss: 0.3922 - val_accuracy: 0.8247 - val_loss: 0.4384
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8126 - loss: 0.4084 - val_accuracy: 0.8247 - val_loss: 0.4389
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8239 - loss: 0.3824 - val_accuracy: 0.8182 - val_loss: 0.4372
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8073 - loss: 0.4007 - val_accuracy: 0.8247 - val_loss: 0.4391

In [ ]:
# i how to select appropriate Optimizer
# No of nodes in a layer
#how do select no of layers
# All in one model

In [ ]:
!pip install keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.7-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.10.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (25.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.14.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.17.0)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2025.8.3)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from optree->keras->keras-tuner) (4.15.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.7-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.1/129.1 kB 2.5 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.7 kt-legacy-1.0.5

In [ ]:
import kerastuner as kt

/tmp/ipython-input-1654478174.py:1: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt

In [ ]:
def build_model(hp):
  model =Sequential()
  model.add(Dense(32,activation='relu',input_dim =8))
  model.add(Dense(1,activation='sigmoid'))
  optimizer=hp.Choice('optimizer',values =['adam','sgd','rmsprop','adadelta'])
  model.compile(optimizer=optimizer,loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [ ]:
tuner =kt.RandomSearch(build_model,objective='val_accuracy',max_trials=5)

Reloading Tuner from ./untitled_project/tuner0.json

In [ ]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

In [ ]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'adam'}

In [ ]:
model =tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7506 - loss: 0.5353 - val_accuracy: 0.7987 - val_loss: 0.4955
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.5132 - val_accuracy: 0.8052 - val_loss: 0.4780
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7735 - loss: 0.4902 - val_accuracy: 0.8052 - val_loss: 0.4644
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7380 - loss: 0.5121 - val_accuracy: 0.8052 - val_loss: 0.4552
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7477 - loss: 0.4899 - val_accuracy: 0.8117 - val_loss: 0.4511
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7685 - loss: 0.4719 - val_accuracy: 0.8117 - val_loss: 0.4457
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7569 - loss: 0.4845 - val_accuracy: 0.8117 - val_loss: 0.4412
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7610 - loss: 0.4636 - val_accuracy: 0.8117 - val_loss: 0.4363
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7565 - loss: 0.4768 - val_accuracy: 0.8117 - val_loss: 0.4347
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7702 - loss: 0.4820 - val_accuracy: 0.8117 - val_loss: 0.4318
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7646 - loss: 0.4777 - val_accuracy: 0.8117 - val_loss: 0.4303
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7887 - loss: 0.4496 - val_accuracy: 0.8117 - val_loss: 0.4276
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7722 - loss: 0.4757 - val_accuracy: 0.8117 - val_loss: 0.4271
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7599 - loss: 0.4769 - val_accuracy: 0.8117 - val_loss: 0.4264
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7827 - loss: 0.4434 - val_accuracy: 0.8117 - val_loss: 0.4270
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7589 - loss: 0.4828 - val_accuracy: 0.8182 - val_loss: 0.4272
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7495 - loss: 0.5030 - val_accuracy: 0.8117 - val_loss: 0.4253
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7807 - loss: 0.4596 - val_accuracy: 0.8117 - val_loss: 0.4248
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7638 - loss: 0.4732 - val_accuracy: 0.8117 - val_loss: 0.4251
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7678 - loss: 0.4690 - val_accuracy: 0.8182 - val_loss: 0.4242
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7809 - loss: 0.4534 - val_accuracy: 0.8247 - val_loss: 0.4255
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7931 - loss: 0.4574 - val_accuracy: 0.8247 - val_loss: 0.4252
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8005 - loss: 0.4076 - val_accuracy: 0.8247 - val_loss: 0.4258
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8031 - loss: 0.4350 - val_accuracy: 0.8247 - val_loss: 0.4269
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7850 - loss: 0.4473 - val_accuracy: 0.8247 - val_loss: 0.4300
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7776 - loss: 0.4567 - val_accuracy: 0.8247 - val_loss: 0.4282
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8002 - loss: 0.4464 - val_accuracy: 0.8247 - val_loss: 0.4274
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7712 - loss: 0.4601 - val_accuracy: 0.8182 - val_loss: 0.4284
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7804 - loss: 0.4502 - val_accuracy: 0.8117 - val_loss: 0.4285
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7819 - loss: 0.4571 - val_accuracy: 0.8117 - val_loss: 0.4265
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7849 - loss: 0.4406 - val_accuracy: 0.8117 - val_loss: 0.4270
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7871 - loss: 0.4406 - val_accuracy: 0.8182 - val_loss: 0.4269
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7676 - loss: 0.4509 - val_accuracy: 0.8182 - val_loss: 0.4274
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8043 - loss: 0.4079 - val_accuracy: 0.8052 - val_loss: 0.4277
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7839 - loss: 0.4205 - val_accuracy: 0.8117 - val_loss: 0.4281
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7864 - loss: 0.4421 - val_accuracy: 0.8052 - val_loss: 0.4290
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7889 - loss: 0.4285 - val_accuracy: 0.8117 - val_loss: 0.4286
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4364 - val_accuracy: 0.8117 - val_loss: 0.4289
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7963 - loss: 0.4462 - val_accuracy: 0.8117 - val_loss: 0.4289
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7864 - loss: 0.4298 - val_accuracy: 0.8117 - val_loss: 0.4305
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7748 - loss: 0.4486 - val_accuracy: 0.8117 - val_loss: 0.4289
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7799 - loss: 0.4443 - val_accuracy: 0.8117 - val_loss: 0.4286
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7914 - loss: 0.4259 - val_accuracy: 0.8182 - val_loss: 0.4266
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4221 - val_accuracy: 0.8117 - val_loss: 0.4283
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7721 - loss: 0.4622 - val_accuracy: 0.8117 - val_loss: 0.4286
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8007 - loss: 0.4219 - val_accuracy: 0.8117 - val_loss: 0.4271
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7837 - loss: 0.4285 - val_accuracy: 0.8117 - val_loss: 0.4293
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7886 - loss: 0.4354 - val_accuracy: 0.8182 - val_loss: 0.4296
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8026 - loss: 0.4326 - val_accuracy: 0.7987 - val_loss: 0.4321
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8095 - loss: 0.4208 - val_accuracy: 0.7987 - val_loss: 0.4323
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7967 - loss: 0.4345 - val_accuracy: 0.8052 - val_loss: 0.4308
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7878 - loss: 0.4475 - val_accuracy: 0.8117 - val_loss: 0.4314
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8185 - loss: 0.4099 - val_accuracy: 0.8182 - val_loss: 0.4317
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8095 - loss: 0.4050 - val_accuracy: 0.8182 - val_loss: 0.4312
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7752 - loss: 0.4388 - val_accuracy: 0.8052 - val_loss: 0.4306
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8014 - loss: 0.4283 - val_accuracy: 0.8182 - val_loss: 0.4320
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7963 - loss: 0.4291 - val_accuracy: 0.8182 - val_loss: 0.4316
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7994 - loss: 0.4077 - val_accuracy: 0.8247 - val_loss: 0.4328
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8016 - loss: 0.4355 - val_accuracy: 0.8182 - val_loss: 0.4355
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7867 - loss: 0.4374 - val_accuracy: 0.8182 - val_loss: 0.4338
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8041 - loss: 0.4113 - val_accuracy: 0.8247 - val_loss: 0.4341
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7883 - loss: 0.4593 - val_accuracy: 0.8247 - val_loss: 0.4351
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7841 - loss: 0.4356 - val_accuracy: 0.8247 - val_loss: 0.4345
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7805 - loss: 0.4467 - val_accuracy: 0.8247 - val_loss: 0.4355
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4206 - val_accuracy: 0.8117 - val_loss: 0.4345
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7912 - loss: 0.4372 - val_accuracy: 0.8182 - val_loss: 0.4339
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8057 - loss: 0.4253 - val_accuracy: 0.8117 - val_loss: 0.4332
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4315 - val_accuracy: 0.8117 - val_loss: 0.4332
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8312 - loss: 0.4146 - val_accuracy: 0.8117 - val_loss: 0.4338
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8074 - loss: 0.4094 - val_accuracy: 0.8117 - val_loss: 0.4341
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8202 - loss: 0.4232 - val_accuracy: 0.8117 - val_loss: 0.4361
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7897 - loss: 0.4346 - val_accuracy: 0.8117 - val_loss: 0.4377
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8035 - loss: 0.4248 - val_accuracy: 0.8052 - val_loss: 0.4379
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7990 - loss: 0.4154 - val_accuracy: 0.8117 - val_loss: 0.4367
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8188 - loss: 0.4129 - val_accuracy: 0.8182 - val_loss: 0.4366
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7774 - loss: 0.4372 - val_accuracy: 0.8052 - val_loss: 0.4401
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8019 - loss: 0.4199 - val_accuracy: 0.8117 - val_loss: 0.4386
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7935 - loss: 0.4330 - val_accuracy: 0.8117 - val_loss: 0.4384
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8062 - loss: 0.4062 - val_accuracy: 0.8052 - val_loss: 0.4386
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4299 - val_accuracy: 0.8117 - val_loss: 0.4416
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7938 - loss: 0.4289 - val_accuracy: 0.8247 - val_loss: 0.4378
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7983 - loss: 0.4205 - val_accuracy: 0.8117 - val_loss: 0.4367
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7840 - loss: 0.4325 - val_accuracy: 0.8117 - val_loss: 0.4374
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8126 - loss: 0.4163 - val_accuracy: 0.8052 - val_loss: 0.4394
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8135 - loss: 0.4075 - val_accuracy: 0.8052 - val_loss: 0.4396
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7978 - loss: 0.4205 - val_accuracy: 0.8247 - val_loss: 0.4368
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8119 - loss: 0.4046 - val_accuracy: 0.8182 - val_loss: 0.4377
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8005 - loss: 0.4231 - val_accuracy: 0.8052 - val_loss: 0.4394
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7862 - loss: 0.4390 - val_accuracy: 0.8247 - val_loss: 0.4361
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8101 - loss: 0.4116 - val_accuracy: 0.8117 - val_loss: 0.4376
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8124 - loss: 0.3990 - val_accuracy: 0.8117 - val_loss: 0.4370
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8134 - loss: 0.3949 - val_accuracy: 0.8117 - val_loss: 0.4390
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8086 - loss: 0.4291 - val_accuracy: 0.8052 - val_loss: 0.4378
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8193 - loss: 0.3859 - val_accuracy: 0.8052 - val_loss: 0.4396

In [ ]:
def build_model(hp):
  model =Sequential()
  units=hp.Int('units',min_value=8,max_value=128,step =8)
  model.add(Dense(units,activation='relu',input_dim =8))
  model.add(Dense(1,activation='sigmoid'))
  optimizer=hp.Choice('optimizer',values =['adam','sgd','rmsprop','adadelta'])
  model.compile(optimizer=optimizer,loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [66]:
tuner =kt.RandomSearch(build_model,objective='val_accuracy',max_trials=5,directory='myidr',project_name='Salmankhan')

Reloading Tuner from myidr/Salmankhan/tuner0.json

In [64]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

Trial 5 Complete [00h 00m 03s]
val_accuracy: 0.7857142686843872

Best val_accuracy So Far: 0.8051947951316833
Total elapsed time: 00h 00m 15s

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [67]:
tuner.get_best_hyperparameters()[0].values

{'units': 88, 'optimizer': 'rmsprop'}

In [68]:
tuner.get_best_models(num_models=1)[0]

In [70]:
model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8211 - loss: 0.3785 - val_accuracy: 0.8117 - val_loss: 0.4390
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8223 - loss: 0.3946 - val_accuracy: 0.8117 - val_loss: 0.4388
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.8028 - loss: 0.4205 - val_accuracy: 0.8052 - val_loss: 0.4373
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8091 - loss: 0.4064 - val_accuracy: 0.8117 - val_loss: 0.4379
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7936 - loss: 0.4292 - val_accuracy: 0.8117 - val_loss: 0.4376
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8071 - loss: 0.4149 - val_accuracy: 0.7987 - val_loss: 0.4412
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8217 - loss: 0.4150 - val_accuracy: 0.8052 - val_loss: 0.4390
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7938 - loss: 0.4395 - val_accuracy: 0.8117 - val_loss: 0.4406
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8127 - loss: 0.3881 - val_accuracy: 0.8182 - val_loss: 0.4396
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7945 - loss: 0.4327 - val_accuracy: 0.8182 - val_loss: 0.4380
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7967 - loss: 0.4284 - val_accuracy: 0.8182 - val_loss: 0.4402
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8278 - loss: 0.3980 - val_accuracy: 0.8182 - val_loss: 0.4398
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7978 - loss: 0.4104 - val_accuracy: 0.8182 - val_loss: 0.4391
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7844 - loss: 0.4264 - val_accuracy: 0.8182 - val_loss: 0.4391
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7851 - loss: 0.4230 - val_accuracy: 0.8117 - val_loss: 0.4391
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8123 - loss: 0.3811 - val_accuracy: 0.8117 - val_loss: 0.4382
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7904 - loss: 0.4077 - val_accuracy: 0.8117 - val_loss: 0.4386
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7670 - loss: 0.4525 - val_accuracy: 0.7987 - val_loss: 0.4403
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8169 - loss: 0.3908 - val_accuracy: 0.8052 - val_loss: 0.4406
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8104 - loss: 0.3929 - val_accuracy: 0.8117 - val_loss: 0.4403
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8219 - loss: 0.3819 - val_accuracy: 0.8182 - val_loss: 0.4395
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8064 - loss: 0.4127 - val_accuracy: 0.8052 - val_loss: 0.4406
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8198 - loss: 0.3948 - val_accuracy: 0.8182 - val_loss: 0.4406
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8226 - loss: 0.3920 - val_accuracy: 0.8052 - val_loss: 0.4410
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7663 - loss: 0.4599 - val_accuracy: 0.7987 - val_loss: 0.4427
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7927 - loss: 0.4321 - val_accuracy: 0.8117 - val_loss: 0.4423
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8116 - loss: 0.4194 - val_accuracy: 0.8117 - val_loss: 0.4397
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7925 - loss: 0.4292 - val_accuracy: 0.8182 - val_loss: 0.4398
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7890 - loss: 0.4154 - val_accuracy: 0.8182 - val_loss: 0.4415
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7775 - loss: 0.4485 - val_accuracy: 0.8182 - val_loss: 0.4408
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7848 - loss: 0.4259 - val_accuracy: 0.8247 - val_loss: 0.4427
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7713 - loss: 0.4435 - val_accuracy: 0.8247 - val_loss: 0.4403
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8200 - loss: 0.3979 - val_accuracy: 0.8247 - val_loss: 0.4404
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7968 - loss: 0.4177 - val_accuracy: 0.8312 - val_loss: 0.4433
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8026 - loss: 0.4116 - val_accuracy: 0.8247 - val_loss: 0.4433
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7877 - loss: 0.4158 - val_accuracy: 0.8182 - val_loss: 0.4428
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7924 - loss: 0.4254 - val_accuracy: 0.8182 - val_loss: 0.4434
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8167 - loss: 0.3958 - val_accuracy: 0.8182 - val_loss: 0.4441
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8177 - loss: 0.4035 - val_accuracy: 0.8117 - val_loss: 0.4439
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7843 - loss: 0.4456 - val_accuracy: 0.8182 - val_loss: 0.4437
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8102 - loss: 0.4126 - val_accuracy: 0.8182 - val_loss: 0.4450
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7947 - loss: 0.4044 - val_accuracy: 0.8182 - val_loss: 0.4463
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4218 - val_accuracy: 0.8117 - val_loss: 0.4438
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8198 - loss: 0.3967 - val_accuracy: 0.8117 - val_loss: 0.4435
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8015 - loss: 0.4210 - val_accuracy: 0.8117 - val_loss: 0.4444
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7854 - loss: 0.4182 - val_accuracy: 0.8182 - val_loss: 0.4442
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8145 - loss: 0.3853 - val_accuracy: 0.8182 - val_loss: 0.4434
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8175 - loss: 0.3740 - val_accuracy: 0.8182 - val_loss: 0.4441
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7954 - loss: 0.4122 - val_accuracy: 0.8182 - val_loss: 0.4440
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8096 - loss: 0.3947 - val_accuracy: 0.8182 - val_loss: 0.4443
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8074 - loss: 0.3813 - val_accuracy: 0.8182 - val_loss: 0.4466
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8298 - loss: 0.3833 - val_accuracy: 0.8182 - val_loss: 0.4470
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8074 - loss: 0.4038 - val_accuracy: 0.8182 - val_loss: 0.4481
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8051 - loss: 0.4098 - val_accuracy: 0.8247 - val_loss: 0.4501
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8168 - loss: 0.3940 - val_accuracy: 0.8182 - val_loss: 0.4498
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7992 - loss: 0.4265 - val_accuracy: 0.8182 - val_loss: 0.4452
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8254 - loss: 0.3937 - val_accuracy: 0.8182 - val_loss: 0.4438
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8189 - loss: 0.3810 - val_accuracy: 0.8247 - val_loss: 0.4452
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8224 - loss: 0.3897 - val_accuracy: 0.8247 - val_loss: 0.4451
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8084 - loss: 0.4025 - val_accuracy: 0.8182 - val_loss: 0.4478
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8390 - loss: 0.3648 - val_accuracy: 0.8247 - val_loss: 0.4434
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8141 - loss: 0.3955 - val_accuracy: 0.8247 - val_loss: 0.4451
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7848 - loss: 0.4152 - val_accuracy: 0.8247 - val_loss: 0.4460
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7942 - loss: 0.4203 - val_accuracy: 0.8247 - val_loss: 0.4467
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7944 - loss: 0.4142 - val_accuracy: 0.8247 - val_loss: 0.4471
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8083 - loss: 0.4138 - val_accuracy: 0.8247 - val_loss: 0.4447
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7840 - loss: 0.4424 - val_accuracy: 0.8247 - val_loss: 0.4462
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8240 - loss: 0.3767 - val_accuracy: 0.8247 - val_loss: 0.4466
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8116 - loss: 0.3949 - val_accuracy: 0.8247 - val_loss: 0.4476
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8197 - loss: 0.3787 - val_accuracy: 0.8182 - val_loss: 0.4481
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7961 - loss: 0.4060 - val_accuracy: 0.8247 - val_loss: 0.4479
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8151 - loss: 0.3848 - val_accuracy: 0.8247 - val_loss: 0.4474
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4134 - val_accuracy: 0.8247 - val_loss: 0.4483
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8237 - loss: 0.3845 - val_accuracy: 0.8247 - val_loss: 0.4489
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8315 - loss: 0.3724 - val_accuracy: 0.8247 - val_loss: 0.4461
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8067 - loss: 0.4010 - val_accuracy: 0.8247 - val_loss: 0.4460
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8310 - loss: 0.3632 - val_accuracy: 0.8247 - val_loss: 0.4477
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7967 - loss: 0.3948 - val_accuracy: 0.8247 - val_loss: 0.4491
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8355 - loss: 0.3762 - val_accuracy: 0.8247 - val_loss: 0.4511
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8143 - loss: 0.4052 - val_accuracy: 0.8247 - val_loss: 0.4481
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8212 - loss: 0.3807 - val_accuracy: 0.8312 - val_loss: 0.4468
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8220 - loss: 0.4115 - val_accuracy: 0.8247 - val_loss: 0.4511
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8252 - loss: 0.3888 - val_accuracy: 0.8247 - val_loss: 0.4488
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8111 - loss: 0.3911 - val_accuracy: 0.8247 - val_loss: 0.4496
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8120 - loss: 0.3952 - val_accuracy: 0.8247 - val_loss: 0.4506
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8107 - loss: 0.4052 - val_accuracy: 0.8247 - val_loss: 0.4500
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8265 - loss: 0.3710 - val_accuracy: 0.8247 - val_loss: 0.4506
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7908 - loss: 0.4137 - val_accuracy: 0.8247 - val_loss: 0.4541
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4156 - val_accuracy: 0.8247 - val_loss: 0.4532
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8148 - loss: 0.3990 - val_accuracy: 0.8247 - val_loss: 0.4506
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8139 - loss: 0.3982 - val_accuracy: 0.8247 - val_loss: 0.4514
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8324 - loss: 0.3915 - val_accuracy: 0.8247 - val_loss: 0.4497
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8324 - loss: 0.3582 - val_accuracy: 0.8247 - val_loss: 0.4518
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8269 - loss: 0.3914 - val_accuracy: 0.8247 - val_loss: 0.4506

In [88]:
def model_build(hp):
  model =Sequential()
  model.add(Dense(72,activation='relu',input_dim =8))
  for i in range(hp.Int('num_layers',min_value=1,max_value=10)):
      model.add(Dense(72,activation='relu'))
      model.add(Dense(1,activation='sigmoid'))
      model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['accuracy'])
      return model

In [89]:
tuner =kt.RandomSearch(model_build,objective='val_accuracy',max_trials=3,directory='myidr',project_name='Salmankhan2')

Reloading Tuner from myidr/Salmankhan2/tuner0.json

In [90]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

In [91]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 10}

In [93]:
model.fit(X_train,y_train,batch_size=32,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7985 - loss: 0.4007 - val_accuracy: 0.8247 - val_loss: 0.4513
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8206 - loss: 0.3816 - val_accuracy: 0.8247 - val_loss: 0.4550
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8179 - loss: 0.3913 - val_accuracy: 0.8247 - val_loss: 0.4540
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7880 - loss: 0.4231 - val_accuracy: 0.8247 - val_loss: 0.4526
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8085 - loss: 0.3825 - val_accuracy: 0.8247 - val_loss: 0.4523
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8277 - loss: 0.3812 - val_accuracy: 0.8247 - val_loss: 0.4543
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8394 - loss: 0.3814 - val_accuracy: 0.8247 - val_loss: 0.4543
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8365 - loss: 0.4107 - val_accuracy: 0.8247 - val_loss: 0.4583
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8334 - loss: 0.3708 - val_accuracy: 0.8247 - val_loss: 0.4571
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8201 - loss: 0.4047 - val_accuracy: 0.8247 - val_loss: 0.4587
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8298 - loss: 0.4029 - val_accuracy: 0.8247 - val_loss: 0.4541
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8325 - loss: 0.3710 - val_accuracy: 0.8247 - val_loss: 0.4553
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8290 - loss: 0.3764 - val_accuracy: 0.8247 - val_loss: 0.4543
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8242 - loss: 0.3822 - val_accuracy: 0.8247 - val_loss: 0.4534
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8160 - loss: 0.4016 - val_accuracy: 0.8247 - val_loss: 0.4545
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8141 - loss: 0.3914 - val_accuracy: 0.8247 - val_loss: 0.4543
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8507 - loss: 0.3508 - val_accuracy: 0.8247 - val_loss: 0.4524
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8030 - loss: 0.4185 - val_accuracy: 0.8247 - val_loss: 0.4540
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8149 - loss: 0.3895 - val_accuracy: 0.8247 - val_loss: 0.4548
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8278 - loss: 0.3902 - val_accuracy: 0.8247 - val_loss: 0.4553
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8419 - loss: 0.3611 - val_accuracy: 0.8247 - val_loss: 0.4526
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8172 - loss: 0.3899 - val_accuracy: 0.8247 - val_loss: 0.4531
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8235 - loss: 0.3752 - val_accuracy: 0.8247 - val_loss: 0.4555
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8166 - loss: 0.3897 - val_accuracy: 0.8247 - val_loss: 0.4542
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8404 - loss: 0.3494 - val_accuracy: 0.8247 - val_loss: 0.4540
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8339 - loss: 0.3751 - val_accuracy: 0.8247 - val_loss: 0.4544
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8294 - loss: 0.3997 - val_accuracy: 0.8247 - val_loss: 0.4542
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8389 - loss: 0.3726 - val_accuracy: 0.8247 - val_loss: 0.4555
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8422 - loss: 0.3605 - val_accuracy: 0.8247 - val_loss: 0.4559
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8411 - loss: 0.3728 - val_accuracy: 0.8247 - val_loss: 0.4565
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8159 - loss: 0.3775 - val_accuracy: 0.8247 - val_loss: 0.4564
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8473 - loss: 0.3688 - val_accuracy: 0.8247 - val_loss: 0.4595
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8199 - loss: 0.4048 - val_accuracy: 0.8182 - val_loss: 0.4583
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8257 - loss: 0.3593 - val_accuracy: 0.8247 - val_loss: 0.4559
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4129 - val_accuracy: 0.8247 - val_loss: 0.4581
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8327 - loss: 0.3699 - val_accuracy: 0.8247 - val_loss: 0.4562
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8077 - loss: 0.3922 - val_accuracy: 0.8247 - val_loss: 0.4570
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8394 - loss: 0.3861 - val_accuracy: 0.8247 - val_loss: 0.4596
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8365 - loss: 0.3623 - val_accuracy: 0.8247 - val_loss: 0.4577
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8128 - loss: 0.3953 - val_accuracy: 0.8182 - val_loss: 0.4584
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8130 - loss: 0.4083 - val_accuracy: 0.8247 - val_loss: 0.4573
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8097 - loss: 0.4188 - val_accuracy: 0.8247 - val_loss: 0.4612
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8515 - loss: 0.3421 - val_accuracy: 0.8247 - val_loss: 0.4631
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8435 - loss: 0.3498 - val_accuracy: 0.8247 - val_loss: 0.4607
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8278 - loss: 0.3592 - val_accuracy: 0.8247 - val_loss: 0.4600
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8307 - loss: 0.3691 - val_accuracy: 0.8247 - val_loss: 0.4591
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8091 - loss: 0.4218 - val_accuracy: 0.8247 - val_loss: 0.4599
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8292 - loss: 0.3946 - val_accuracy: 0.8247 - val_loss: 0.4585
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8374 - loss: 0.3536 - val_accuracy: 0.8247 - val_loss: 0.4582
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8184 - loss: 0.3805 - val_accuracy: 0.8247 - val_loss: 0.4581
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8476 - loss: 0.3731 - val_accuracy: 0.8247 - val_loss: 0.4609
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8364 - loss: 0.3665 - val_accuracy: 0.8247 - val_loss: 0.4611
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8256 - loss: 0.3882 - val_accuracy: 0.8247 - val_loss: 0.4611
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8329 - loss: 0.3736 - val_accuracy: 0.8247 - val_loss: 0.4611
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8296 - loss: 0.3720 - val_accuracy: 0.8247 - val_loss: 0.4609
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8408 - loss: 0.3734 - val_accuracy: 0.8247 - val_loss: 0.4618
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8487 - loss: 0.3514 - val_accuracy: 0.8247 - val_loss: 0.4617
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8084 - loss: 0.3965 - val_accuracy: 0.8247 - val_loss: 0.4620
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8268 - loss: 0.3655 - val_accuracy: 0.8247 - val_loss: 0.4624
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8300 - loss: 0.3808 - val_accuracy: 0.8247 - val_loss: 0.4632
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8349 - loss: 0.3830 - val_accuracy: 0.8247 - val_loss: 0.4648
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8068 - loss: 0.4284 - val_accuracy: 0.8247 - val_loss: 0.4665
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8001 - loss: 0.4063 - val_accuracy: 0.8247 - val_loss: 0.4674
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8117 - loss: 0.4007 - val_accuracy: 0.8247 - val_loss: 0.4677
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8284 - loss: 0.3784 - val_accuracy: 0.8247 - val_loss: 0.4642
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.8376 - loss: 0.3537 - val_accuracy: 0.8247 - val_loss: 0.4673
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8238 - loss: 0.4003 - val_accuracy: 0.8247 - val_loss: 0.4670
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8336 - loss: 0.3851 - val_accuracy: 0.8247 - val_loss: 0.4633
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8180 - loss: 0.3989 - val_accuracy: 0.8247 - val_loss: 0.4665
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8539 - loss: 0.3580 - val_accuracy: 0.8247 - val_loss: 0.4671
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8300 - loss: 0.3719 - val_accuracy: 0.8247 - val_loss: 0.4679
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8138 - loss: 0.3907 - val_accuracy: 0.8247 - val_loss: 0.4686
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8451 - loss: 0.3784 - val_accuracy: 0.8247 - val_loss: 0.4676
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8149 - loss: 0.3908 - val_accuracy: 0.8247 - val_loss: 0.4672
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8428 - loss: 0.3697 - val_accuracy: 0.8247 - val_loss: 0.4695
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8304 - loss: 0.3759 - val_accuracy: 0.8182 - val_loss: 0.4658
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8314 - loss: 0.3973 - val_accuracy: 0.8247 - val_loss: 0.4679
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8439 - loss: 0.3440 - val_accuracy: 0.8182 - val_loss: 0.4675
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8450 - loss: 0.3510 - val_accuracy: 0.8247 - val_loss: 0.4675
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8070 - loss: 0.3874 - val_accuracy: 0.8247 - val_loss: 0.4651
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8188 - loss: 0.4076 - val_accuracy: 0.8247 - val_loss: 0.4682
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8515 - loss: 0.3518 - val_accuracy: 0.8247 - val_loss: 0.4677
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8434 - loss: 0.3784 - val_accuracy: 0.8247 - val_loss: 0.4684
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8419 - loss: 0.3751 - val_accuracy: 0.8247 - val_loss: 0.4709
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8482 - loss: 0.3651 - val_accuracy: 0.8247 - val_loss: 0.4660
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8486 - loss: 0.3671 - val_accuracy: 0.8247 - val_loss: 0.4680
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8498 - loss: 0.3646 - val_accuracy: 0.8247 - val_loss: 0.4690
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8178 - loss: 0.3994 - val_accuracy: 0.8247 - val_loss: 0.4702
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8423 - loss: 0.3578 - val_accuracy: 0.8247 - val_loss: 0.4690
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8235 - loss: 0.3698 - val_accuracy: 0.8247 - val_loss: 0.4704
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8359 - loss: 0.3655 - val_accuracy: 0.8247 - val_loss: 0.4685
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8212 - loss: 0.3875 - val_accuracy: 0.8247 - val_loss: 0.4690
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8335 - loss: 0.3870 - val_accuracy: 0.8247 - val_loss: 0.4712
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.8304 - loss: 0.3957 - val_accuracy: 0.8247 - val_loss: 0.4703

In [116]:
def build_model(hp):
  model =Sequential()
  counter =0
  for i in range(hp.Int('num_layers',min_value =1,max_value=10)):
    if counter ==0:
      model.add(Dense(hp.Int('units'+str(i),min_value=8,max_value=128,step=8),
                      activation=hp.Choice('activation'+str(i),values=['relu','tanh','sigmoid']),input_dim=8))
      model.add(Dropout(hp.Choice('dropout_'+str(i),values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
    else:
        model.add(Dense(hp.Int('units'+str(i),min_value=8,max_value=128,step=8),
                        activation=hp.Choice('activation'+str(i),values=['relu','tanh','sigmoid'])))
        model.add(Dropout(hp.Choice('dropout_'+str(i),values=[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
    counter+=1

  model.add(Dense(1,activation='sigmoid'))
  model.compile(optimizer=hp.Choice('optimizer',values=['adam','sgd','rmsprop','adadelta']),loss='binary_crossentropy',metrics=['accuracy'])
  return model

In [120]:
tuner =kt.RandomSearch(build_model,objective='val_accuracy',max_trials=3,directory='myidr',project_name='Salmankhan4')

Reloading Tuner from myidr/Salmankhan4/tuner0.json

In [121]:
tuner.search(X_train,y_train,epochs=5,validation_data=(X_test,y_test))

In [119]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 3,
 'units0': 8,
 'activation0': 'relu',
 'dropout_0': 0.7,
 'optimizer': 'rmsprop',
 'units1': 8,
 'activation1': 'relu',
 'dropout_1': 0.1,
 'units2': 8,
 'activation2': 'relu',
 'dropout_2': 0.1}

In [122]:
model =tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:802: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [123]:
model.fit(X_train,y_train,epochs=100,initial_epoch=6,validation_data=(X_test,y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - accuracy: 0.6629 - loss: 0.6345 - val_accuracy: 0.7078 - val_loss: 0.6083
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6551 - loss: 0.6506 - val_accuracy: 0.7078 - val_loss: 0.6043
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6715 - loss: 0.6190 - val_accuracy: 0.7143 - val_loss: 0.5959
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6396 - loss: 0.6337 - val_accuracy: 0.7143 - val_loss: 0.5934
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6259 - loss: 0.6229 - val_accuracy: 0.7143 - val_loss: 0.5886
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6584 - loss: 0.6310 - val_accuracy: 0.7208 - val_loss: 0.5841
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6502 - loss: 0.6219 - val_accuracy: 0.7078 - val_loss: 0.5788
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6583 - loss: 0.6298 - val_accuracy: 0.7143 - val_loss: 0.5716
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6542 - loss: 0.6356 - val_accuracy: 0.7338 - val_loss: 0.5708
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7092 - loss: 0.5969 - val_accuracy: 0.7338 - val_loss: 0.5644
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6518 - loss: 0.6126 - val_accuracy: 0.7532 - val_loss: 0.5566
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6557 - loss: 0.6006 - val_accuracy: 0.7468 - val_loss: 0.5487
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6699 - loss: 0.6097 - val_accuracy: 0.7468 - val_loss: 0.5524
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6505 - loss: 0.6300 - val_accuracy: 0.7597 - val_loss: 0.5504
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6610 - loss: 0.6087 - val_accuracy: 0.7468 - val_loss: 0.5462
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6540 - loss: 0.6058 - val_accuracy: 0.7662 - val_loss: 0.5384
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6522 - loss: 0.6511 - val_accuracy: 0.7662 - val_loss: 0.5356
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6383 - loss: 0.6342 - val_accuracy: 0.7662 - val_loss: 0.5324
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6683 - loss: 0.6075 - val_accuracy: 0.7532 - val_loss: 0.5286
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6631 - loss: 0.6155 - val_accuracy: 0.7532 - val_loss: 0.5251
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6376 - loss: 0.6163 - val_accuracy: 0.7532 - val_loss: 0.5213
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6571 - loss: 0.5960 - val_accuracy: 0.7597 - val_loss: 0.5156
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6711 - loss: 0.6116 - val_accuracy: 0.7532 - val_loss: 0.5183
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6556 - loss: 0.6242 - val_accuracy: 0.7532 - val_loss: 0.5181
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7114 - loss: 0.5900 - val_accuracy: 0.7597 - val_loss: 0.5214
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7011 - loss: 0.6150 - val_accuracy: 0.7597 - val_loss: 0.5215
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6757 - loss: 0.5874 - val_accuracy: 0.7727 - val_loss: 0.5185
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6582 - loss: 0.6244 - val_accuracy: 0.7727 - val_loss: 0.5205
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6676 - loss: 0.6016 - val_accuracy: 0.7727 - val_loss: 0.5154
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6952 - loss: 0.5679 - val_accuracy: 0.7792 - val_loss: 0.5099
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6437 - loss: 0.5883 - val_accuracy: 0.7727 - val_loss: 0.5094
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6743 - loss: 0.6049 - val_accuracy: 0.7857 - val_loss: 0.5101
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6854 - loss: 0.6339 - val_accuracy: 0.7792 - val_loss: 0.5100
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6918 - loss: 0.5993 - val_accuracy: 0.7727 - val_loss: 0.5056
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6544 - loss: 0.5972 - val_accuracy: 0.7792 - val_loss: 0.5028
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6895 - loss: 0.5839 - val_accuracy: 0.7662 - val_loss: 0.4963
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6434 - loss: 0.6152 - val_accuracy: 0.7792 - val_loss: 0.5012
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6978 - loss: 0.5790 - val_accuracy: 0.7662 - val_loss: 0.5011
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6470 - loss: 0.6162 - val_accuracy: 0.7727 - val_loss: 0.5004
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7007 - loss: 0.5650 - val_accuracy: 0.7792 - val_loss: 0.4973
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6662 - loss: 0.5747 - val_accuracy: 0.7792 - val_loss: 0.4923
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6882 - loss: 0.5622 - val_accuracy: 0.7857 - val_loss: 0.4879
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6715 - loss: 0.6123 - val_accuracy: 0.7662 - val_loss: 0.4909
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.7257 - loss: 0.5635 - val_accuracy: 0.7857 - val_loss: 0.4922
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6963 - loss: 0.5939 - val_accuracy: 0.7857 - val_loss: 0.4910
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6810 - loss: 0.5575 - val_accuracy: 0.7792 - val_loss: 0.4867
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6937 - loss: 0.5602 - val_accuracy: 0.7857 - val_loss: 0.4834
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6614 - loss: 0.5760 - val_accuracy: 0.7727 - val_loss: 0.4835
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6896 - loss: 0.5909 - val_accuracy: 0.7792 - val_loss: 0.4897
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6779 - loss: 0.5863 - val_accuracy: 0.7792 - val_loss: 0.4879
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6873 - loss: 0.5786 - val_accuracy: 0.7857 - val_loss: 0.4873
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6796 - loss: 0.5736 - val_accuracy: 0.7727 - val_loss: 0.4883
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6951 - loss: 0.5739 - val_accuracy: 0.7792 - val_loss: 0.4852
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6581 - loss: 0.6185 - val_accuracy: 0.7922 - val_loss: 0.4855
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7009 - loss: 0.5689 - val_accuracy: 0.7922 - val_loss: 0.4784
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6662 - loss: 0.5869 - val_accuracy: 0.7857 - val_loss: 0.4791
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6559 - loss: 0.5863 - val_accuracy: 0.7857 - val_loss: 0.4785
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7226 - loss: 0.5473 - val_accuracy: 0.7857 - val_loss: 0.4749
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7005 - loss: 0.5762 - val_accuracy: 0.8117 - val_loss: 0.4739
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7034 - loss: 0.5582 - val_accuracy: 0.8052 - val_loss: 0.4752
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6812 - loss: 0.5630 - val_accuracy: 0.8182 - val_loss: 0.4727
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6939 - loss: 0.5557 - val_accuracy: 0.8182 - val_loss: 0.4694
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7051 - loss: 0.5538 - val_accuracy: 0.8247 - val_loss: 0.4705
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6832 - loss: 0.5665 - val_accuracy: 0.8247 - val_loss: 0.4692
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6637 - loss: 0.5889 - val_accuracy: 0.8182 - val_loss: 0.4684
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6920 - loss: 0.5678 - val_accuracy: 0.8117 - val_loss: 0.4705
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6912 - loss: 0.5625 - val_accuracy: 0.8052 - val_loss: 0.4710
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7022 - loss: 0.5567 - val_accuracy: 0.7987 - val_loss: 0.4701
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7040 - loss: 0.5680 - val_accuracy: 0.7987 - val_loss: 0.4676
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6960 - loss: 0.5518 - val_accuracy: 0.8052 - val_loss: 0.4677
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7097 - loss: 0.5348 - val_accuracy: 0.8052 - val_loss: 0.4646
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7040 - loss: 0.5536 - val_accuracy: 0.8052 - val_loss: 0.4622
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7002 - loss: 0.5444 - val_accuracy: 0.8052 - val_loss: 0.4613
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7115 - loss: 0.5623 - val_accuracy: 0.8052 - val_loss: 0.4635
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7357 - loss: 0.5341 - val_accuracy: 0.8052 - val_loss: 0.4630
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7475 - loss: 0.4983 - val_accuracy: 0.8117 - val_loss: 0.4614
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7102 - loss: 0.5543 - val_accuracy: 0.8117 - val_loss: 0.4624
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7395 - loss: 0.5343 - val_accuracy: 0.8052 - val_loss: 0.4638
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7197 - loss: 0.5437 - val_accuracy: 0.8052 - val_loss: 0.4645
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7091 - loss: 0.5561 - val_accuracy: 0.8052 - val_loss: 0.4606
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7022 - loss: 0.5528 - val_accuracy: 0.8052 - val_loss: 0.4600
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7012 - loss: 0.5631 - val_accuracy: 0.8117 - val_loss: 0.4612
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6719 - loss: 0.5610 - val_accuracy: 0.8052 - val_loss: 0.4654
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7127 - loss: 0.5568 - val_accuracy: 0.7987 - val_loss: 0.4637
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6577 - loss: 0.5830 - val_accuracy: 0.7987 - val_loss: 0.4616
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7273 - loss: 0.5239 - val_accuracy: 0.8052 - val_loss: 0.4620
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7094 - loss: 0.5389 - val_accuracy: 0.8117 - val_loss: 0.4614
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.6955 - loss: 0.5708 - val_accuracy: 0.8247 - val_loss: 0.4630
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7094 - loss: 0.5886 - val_accuracy: 0.8247 - val_loss: 0.4647
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7469 - loss: 0.5193 - val_accuracy: 0.8247 - val_loss: 0.4625
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7343 - loss: 0.5382 - val_accuracy: 0.8312 - val_loss: 0.4625
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7124 - loss: 0.5517 - val_accuracy: 0.8247 - val_loss: 0.4628
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7056 - loss: 0.5537 - val_accuracy: 0.8247 - val_loss: 0.4626
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7161 - loss: 0.5538 - val_accuracy: 0.8247 - val_loss: 0.4618